name: keyboard_attachable
description: A Flutter package to build widgets that can be attached to the soft keyboard.
version: 2.2.0
homepage: https://github.com/drogel/keyboard_attachable

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
